apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-code-pvc
spec:
  accessModes:
    - ReadWriteMany  # Permite que un solo nodo lea y escriba en el volumen
  resources:
    requests:
      storage: 1Gi  # Tamaño del volumen
